/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_co_therhys_MD_Converter */

#ifndef _Included_uk_co_therhys_MD_Converter
#define _Included_uk_co_therhys_MD_Converter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_co_therhys_MD_Converter
 * Method:    md2html
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_co_therhys_MD_Converter_md2html
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
